apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-dev.yaml
- path: service-dev.yaml
- path: deploymentB-dev.yaml
- path: serviceB-dev.yaml
