apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webb
  template:
    metadata:
      labels:
        app: webb
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80